FROM node:6

COPY app beepaste/app
# COPY docs beepaste/docs
COPY internals beepaste/internals
COPY package.json beepaste/package.json
# COPY build beepaste/build
COPY server beepaste/server
COPY static beepaste/static
COPY views beepaste/views

WORKDIR beepaste/

# ENV NODE_ENV production

RUN npm install
RUN npm run build

EXPOSE 3000

ENTRYPOINT ["npm", "run", "start:prod"]
